<?php echo $this->doctype(); ?>
<?php
// module/Application/view/layout/layout.phtml:
$firephp = \FirePHP::getInstance(true);
$firephp->info($this->locale);
$firephp->info($locale);
?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/style.css')
                    ->appendStylesheet($this->basePath() . '/css/restaurant.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home', array('locale' => $this->locale)); ?>"><?php echo $this->translate('Skeleton Application') ?></a>

          <div class="dropdown" style="float:right">
              <?php echo $this->partial('layout/languages.phtml', array(
                    'locales' => $this->locales,
                    'selected' => $this->locale,
              )); ?>
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home', array('locale' => $this->locale)); ?>"><?php echo $this->translate('Home') ?></a></li>
              <li class=""><a href="<?php echo $this->url('restaurant/orders/make', array('locale' => $this->locale)); ?>"><?php echo $this->translate('Make an order') ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

<?php

if ($this->messages || $this->errors) {
    if (is_array($this->messages)) {
        foreach($this->messages as $message)
        {
            echo '<div class="alert alert-success fade in">' .
                    '<button data-dismiss="alert" class="close" type="button">×</button>' .
                    $message .
                '</div>';
        }
    }

    if (is_array($this->errors)) {
        foreach($this->errors as $error)
        {
            echo '<div class="alert alert-error fade in">' .
                    '<button data-dismiss="alert" class="close" type="button">×</button>' .
                    $error .
                '</div>';
        }
    }
}
?>

      <?php echo $this->content; ?>

      <hr>

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
