<?php
$title = 'Add new song';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($album->title); ?></h1>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$form = $this->form;
$form->setAttribute('action',
    $this->url('song', array('action' => 'add', 'album_id' => $album->id))
);
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
